AMOUNT_SIMULATIONS = 100

SIMULATION_MONTHS = 12
SIMULATION_DAYS = SIMULATION_MONTHS * 30
SIMULATION_HOURS = SIMULATION_DAYS * 24

# LATEX formats table to copy paste in Latex-doc
LATEX = False
OVERVIEW = True

ARRIVAL_BASED = True
DEPARTURE_BASED = False